// <auto-generated />
using EfCoreCompiledModelNaming;
using EfCoreCompiledModelNaming.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(LanguageDbContext), typeof(LanguageDbContextModel))]
