// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace EfCoreCompiledModelNaming.CompiledModels
{
    public partial class LanguageDbContextModel
    {
        private LanguageDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("4e0435a3-8bde-4ae1-a60a-036ccd8aa03e"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var sentence = SentenceEntityType.Create(this);

            SentenceEntityType.CreateAnnotations(sentence);

            AddAnnotation("ProductVersion", "9.0.0-rc.2.24474.1");
        }
    }
}
